name: Run Python script

on:

  workflow_dispatch:

    inputs:

      EnterNumber:

        description: 'find the biggest number'    

        required: true

        default: 5

        type: input

env:

  SCRIPT_NAME: mohit.py

  NUMBER: ${{ github.event.inputs.EnterNumber }}

jobs:

  run-script:

    runs-on: ubuntu-latest

   

    steps:

   

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

        with:

          python-version: '3.7'

      - name: Run python script

        run: |

          cd scripts

          python $SCRIPT_NAME $NUMBER